name = "policy-brain"
main = "src/index.js"
compatibility_date = "2026-06-30"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "policy_brain"
bucket_name = "policy-brain"

{
  "observability": {
    "enabled": false,
    "head_sampling_rate": 1,
    "logs": {
      "enabled": true,
      "head_sampling_rate": 1,
      "persist": true,
      "invocation_logs": true
    },
    "traces": {
      "enabled": false,
      "persist": true,
      "head_sampling_rate": 1
    }
  }
}
